title: "<strong>So Yeon</strong>'s Resume"
description: "A simple online resume"
url: "https://soyeonkimcs.github.io/PersonalWebsite"
baseurl: "/resume"
remote_theme: "LeNPaul/academic"
plugins:
  - jekyll-remote-theme
